### ISSUE TITLE
Possibility to insert a bibliography item inline, with footnote reference disabled (=manual bibliography with generated style)

### ISSUE THREAD

**Issue by smarie** [shyamd/mkdocs-bibtex#225]
Hi, thanks a lot again for this plugin ! I am trying to use it to create a simple publications page for my personal website. Basically I would just like to create a page with a few sections, and insert in each section a bullet list with bibliographic items styled correctly leveraging pandoc + CSL.

I cannot manage to get it work because

 - if I do not cite anything from the .bib file, nothing is added into the generated markdown.
 - if I cite them, the generateg markdown is entirely managed by mkdocs-bibtex and therefore cannot be organized by type (journal, conferences, etc.). Plus, the citation has to go somewhere.

The current workaround I found is

 - to create a local copy of the APA style and edit the `<citation>` entry so that it is identical to `<bibliography>` (ugly !)
 - to set `bib_by_default=false`

Still, the result is not ideal. Indeed `bib_by_default=false` still inserts the footnotes references `[^1]`, and since the bib is not generated they hang here in the resulting page

![image](https://github.com/shyamd/mkdocs-bibtex/assets/3236794/92c58e15-8947-4b13-b375-7000fb0b489d)

I see two features to create to get to something working:

 - adding a config option, or better a markdown hint, to tell `mkdocs-bibtex` that a specific citation key should be rendered inline using the "bibliography" style and not the "citation" style. For example `[@foo2019]` could be transformed as `[@foo2019|b]` where `|` denotes advanced options, and `b` denotes bibliography style.
 - adding a config option, or better a markdown hint as above, to tell `mkdocs-bibtex` to skip adding the markdown footnote `[^1]`.

The combination of these two options would be reaching my objective, which is to insert at any place in the markdown document, an inlined bibliography item with the styling done by pandoc.

If you are ok with the above two features, I can make a pull request.

**Comment by shyamd** [comment]
Your solution sounds good to me. Please make a PR and thanks for your contributions.

**Comment by shyamd** [comment]
This should be working as of v4.1

**Comment by smarie** [comment]
Thanks a lot to both of you ! I'll check it out

**Comment by smarie** [comment]
Hi there, I tried the feature today.

- if I cite something as `[@cite1]` the full csl-styled bib entry text is entered
- if I cite something as `@cite1` I get this error:

```
DEBUG   -  Inline cache: {'[@cite1]': '(here the full citation styled correctly)'}
DEBUG   -  Reference cache: {}
Traceback (most recent call last):
  File "<path>\mkdocs_bibtex\plugin.py", line 157, in on_page_markdown
    replacement = self.registry.reference_text(ref)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<path>\mkdocs_bibtex\registry.py", line 129, in reference_text
    return self._reference_cache[citation.key]
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'cite1'
ERROR   -  [22:04:24] An error happened during the rebuild. The server will appear stuck until build errors are resolved.
```

any idea about why this happens and what should happen ? I do not clearly understand what should happen in both situations, from the doc. Note that if I set `enable_inline_citations=false` then no error happens anymore (but the citation is not converted)

Thanks in advance for your help !
